Add ability to send only errors as logs
DataDog/jmeter-datadog-backend-listener pull request #48
Opened 2023-11-06 21:25 UTC by arustamov

### Requirements for Contributing to this repository

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix one issue at the time.
* The pull request must update the test suite to demonstrate the changed functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see [CONTRIBUTING](/README.md#contributing). 

### What does this PR do?

https://github.com/DataDog/jmeter-datadog-backend-listener/issues/47

### Description of the Change

<img width="1260" alt="Screenshot 2023-11-06 at 22 02 08" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/c1187125-871a-4024-b12f-e88054778679">
<img width="1268" alt="Screenshot 2023-11-06 at 22 02 22" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/892189ed-56f1-45da-9e37-944bb0a4d952">
<img width="1268" alt="Screenshot 2023-11-06 at 22 02 28" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/eb7edc0e-55e1-4ba3-96c0-a2471dac4f65">
<img width="1268" alt="Screenshot 2023-11-06 at 22 02 34" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/7ddb4654-69c2-489f-a3b4-14cdd4c80d97">
<img width="1518" alt="Screenshot 2023-11-06 at 22 03 38" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/5b4ee87e-6a63-40d1-af3a-68a69a4b5df9">
<img width="840" alt="Screenshot 2023-11-06 at 22 03 09" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/3acaa76d-c8d5-4300-8ced-2b24469b7623">

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Additional Notes

### Review checklist (to be filled by reviewers)

- [ ] Feature or bug fix MUST have appropriate tests (unit, integration, etc...)
- [ ] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [ ] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [ ] PR should not have `do-not-merge/` label attached.
- [ ] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

2023-11-07 16:36 UTC, alopezz reviewed
Thanks for your contribution, this looks helpful! However:

- Can we avoid all the formatting changes in unrelated code? They make the diff larger than necessary and harder to spot what has actually change.
- Can we add tests for the new feature? I see there's a new test but it only checks for configuration errors.
- I wonder if it would make sense to make this a bit more flexible and configurable w.r.t. which codes result in logs being sent. What do you think?

2023-11-07 19:02 UTC, arustamov commented
Hi @alopezz , thanks for the review

1. Pushed reverting extra code formatting applied by the default IDEA config
2. The new test testSendOnlyErrorsAsLogsNotBoolean has been added similar to the other ones boolean-based like testSendResultsAsLogsNotBoolean and testIncludeSubresultsNotBoolean.
I don't see any sophisticated test coverage around this so I would really like please not overcomplicate for the specific feature being added now
3. As to the exact solution, I was considering going with regex pattern-based config similar to the sampler filter. The key difference here is that we have not only HTTP code responses but also non-HTTP ones. 
So going with boolean solution saves us from rather complicated pattern to put here as the default value. In addition to this possible non-HTTP responses might have values that are hard to know in advance to config to be able to capture as logs

2023-11-07 20:05 UTC, arustamov commented
> Thanks for your contribution, this looks helpful! However:
> 
> * Can we avoid all the formatting changes in unrelated code? They make the diff larger than necessary and harder to spot what has actually change.
> * Can we add tests for the new feature? I see there's a new test but it only checks for configuration errors.
> * I wonder if it would make sense to make this a bit more flexible and configurable w.r.t. which codes result in logs being sent. What do you think?

2023-11-08 13:30 UTC, arustamov commented
Adding the default behavior as an extra evidense
<img width="1263" alt="Screenshot 2023-11-08 at 14 26 08" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/50df822d-fa0c-480d-a6bd-784501394862">
<img width="731" alt="Screenshot 2023-11-08 at 14 29 31" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/f5d1c8a8-c3d8-4e8b-b9bc-204384a1d635">
<img width="1512" alt="Screenshot 2023-11-08 at 14 30 03" src="https://github.com/DataDog/jmeter-datadog-backend-listener/assets/5088933/9718d5ef-e100-4774-844b-68c5127618f4">

2023-11-08 13:55 UTC, alopezz commented
> 1. Pushed reverting extra code formatting applied by the default IDEA config

I still see many formatting changes that are unrelated to the PR's goal (the markdown files, the import order somewhere else...). I apologize for not having an automated formatting setup for this project at this point; any "general reformatting" change should be in a separate PR if we ever set that up, not a part of a feature PR.

> 2. The new test testSendOnlyErrorsAsLogsNotBoolean has been added similar to the other ones boolean-based like testSendResultsAsLogsNotBoolean and testIncludeSubresultsNotBoolean.
>    I don't see any sophisticated test coverage around this so I would really like please not overcomplicate for the specific feature being added now

We do have tests for similar cases. See, for example, https://github.com/DataDog/jmeter-datadog-backend-listener/blob/a18e76ec25e121f31207642c895e208a13a15a47/src/test/java/org/datadog/jmeter/plugins/DatadogBackendClientTest.java#L191-L197

Writing tests is part of our [contributing guidelines](https://github.com/DataDog/jmeter-datadog-backend-listener#pull-requests) and a good way to ensure the feature works as advertised without having to manually test it.

> 3. As to the exact solution, I was considering going with regex pattern-based config similar to the sampler filter. The key difference here is that we have not only HTTP code responses but also non-HTTP ones.
>    So going with boolean solution saves us from rather complicated pattern to put here as the default value. In addition to this possible non-HTTP responses might have values that are hard to know in advance to config to be able to capture as logs

That's the kind of idea that I had in mind, too. A way that this might work is if we have a regex pattern for exclusion, defaulting to an empty string (meaning the current default behavior of sending all results), and documenting the pattern for errors as an example. Wouldn't that work well enough? Otherwise we're setting on a definition of "error" that I'm not sure is general enough (though I'm not a JMeter user so I may miss some context).

2023-11-10 11:13 UTC, alopezz requested changes
Thanks, nice work! This is pretty much ready to go, just a suggestion to improve the option's description and we'll merge it.

2023-11-10 11:13 UTC, alopezz commented on README.md
> +|excludeLogsResponseCodeRegex|false|`""`| By default if send test results as log events enabled, then all logs are reported to Datadog. To exclude based on response code of sample result, set regex h
```suggestion
|excludeLogsResponseCodeRegex|false|`""`| Setting `sendResultsAsLogs` will submit all results as logs to Datadog by default. This option lets you exclude results whose response code matches a given regex. For example, you may set this option to `[123][0-5][0-9]` to only submit errors.|
```

2023-11-13 09:30 UTC, merged